// AUTO-GENERATED by generate-snippets.mjs on 2025-10-17T13:39:33.681Z
// Source: ListControls.tsx
// Do not edit this file directly.

const snippet = `import React from 'react';
import { Paper, Typography, TextField, Box } from '@mui/material';
import styles from 'MemoizedComponents.module.scss';

interface ListControlsProps {
    filterText: string;
    onFilterChange: (value: string) => void;
    itemCount: number;
    lastClickedId: number | null;
}

const ListControls: React.FC<ListControlsProps> = ({
    filterText,
    onFilterChange,
    itemCount,
    lastClickedId
}) => {
    return (
        <Paper className={\`\${styles.card} \${styles.cardBlue} \${styles.cardParent}\`}>
            <Typography variant="h6" gutterBottom className={\`\${styles.title} \${styles.titleBlue}\`}>
                🎛️ List Controls
            </Typography>
            <Box className={styles.parentControls}>
                <TextField
                    label="Filter Text (triggers all regular list items to re-render)"
                    value={filterText}
                    onChange={(e) => onFilterChange(e.target.value)}
                    fullWidth
                    className={styles.textFieldBlue}
                />
                <Typography className={styles.infoText}>
                    <strong>Total Items:</strong> {itemCount}
                </Typography>
                <Typography className={styles.infoText}>
                    <strong>Last Clicked Item ID:</strong> {lastClickedId ?? 'None'}
                </Typography>
            </Box>
        </Paper>
    );
};

export default ListControls;
`;

export default snippet;
