// AUTO-GENERATED by generate-snippets.mjs on 2025-10-17T13:39:33.681Z
// Source: MemoizedListItem.tsx
// Do not edit this file directly.

const snippet = `import React, { memo } from 'react';
import { Paper, Typography, Button, Collapse, Box } from '@mui/material';
import RenderCount from '../../../overall/RenderCount';
import styles from 'MemoizedComponents.module.scss';

interface MemoizedListItemProps {
    id: number;
    title: string;
    description: string;
    expanded: boolean;
    onToggle: () => void;
}

const MemoizedListItem: React.FC<MemoizedListItemProps> = memo(({ id, title, description, expanded, onToggle }) => {
    return (
        <Paper className={\`\${styles.card} \${styles.cardGreen}\`} sx={{ m: 0, mb: 0 }}>
            <RenderCount componentName={\`MemoizedListItem-\${id}\`} />
            <Box sx={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                <Typography variant="h6" className={\`\${styles.title} \${styles.titleGreen}\`}>
                    {title}
                </Typography>
                <Button 
                    onClick={onToggle}
                    sx={{ 
                        color: '#66bb6a',
                        minWidth: '40px',
                        fontSize: '1.2rem'
                    }}
                >
                    {expanded ? '▲' : '▼'}
                </Button>
            </Box>
            <Collapse in={expanded}>
                <Typography 
                    variant="body2" 
                    className={styles.infoText}
                    sx={{ mt: 2 }}
                >
                    {description}
                </Typography>
            </Collapse>
        </Paper>
    );
});

MemoizedListItem.displayName = 'MemoizedListItem';

export default MemoizedListItem;
`;

export default snippet;
