// AUTO-GENERATED by generate-snippets.mjs on 2025-10-17T13:39:33.681Z
// Source: OptimizedListItem.tsx
// Do not edit this file directly.

const snippet = `import React, { memo, useCallback } from 'react';
import { Paper, Typography, Button, Collapse, Box } from '@mui/material';
import RenderCount from '../../../overall/RenderCount';
import styles from 'MemoizedComponents.module.scss';

interface OptimizedListItemProps {
    id: number;
    title: string;
    description: string;
    expanded: boolean;
    onToggle: () => void;
    onItemClick: (id: number) => void;
}

const OptimizedListItem: React.FC<OptimizedListItemProps> = memo(({ id, title, description, expanded, onToggle, onItemClick }) => {
    const handleToggle = useCallback(() => {
        onToggle();
        onItemClick(id);
    }, [id, onToggle, onItemClick]);

    return (
        <Paper className={\`\${styles.card} \${styles.cardPurple}\`} sx={{ m: 0, mb: 0 }}>
            <RenderCount componentName={\`OptimizedListItem-\${id}\`} />
            <Box sx={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                <Typography variant="h6" className={\`\${styles.title} \${styles.titlePurple}\`}>
                    {title}
                </Typography>
                <Button 
                    onClick={handleToggle}
                    sx={{ 
                        color: '#ba68c8',
                        minWidth: '40px',
                        fontSize: '1.2rem'
                    }}
                >
                    {expanded ? '▲' : '▼'}
                </Button>
            </Box>
            <Collapse in={expanded}>
                <Typography 
                    variant="body2" 
                    className={styles.infoText}
                    sx={{ mt: 2 }}
                >
                    {description}
                </Typography>
            </Collapse>
        </Paper>
    );
});

OptimizedListItem.displayName = 'OptimizedListItem';

export default OptimizedListItem;
`;

export default snippet;
