// AUTO-GENERATED by generate-snippets.js on 2025-10-23T16:21:58.751Z
// Source: ListItem.tsx
// Do not edit this file directly.

const snippet = `import React from 'react';
import { Paper, Typography, Button, Collapse, Box } from '@mui/material';
import styles from 'MemoizedComponents.module.scss';
import { useAppSelector, useAppDispatch } from 'store/hooks';
import { selectIsExpanded, setExpandedId } from '../expandableList.slice';

interface ListItemProps {
    id: number;
    title: string;
    description: string;
}

const ListItem: React.FC<ListItemProps> = ({ id, title, description }) => {
    const dispatch = useAppDispatch();
    const isExpanded = useAppSelector(selectIsExpanded(id));
    const onToggle = () => {
        dispatch(setExpandedId(id));
        // Dispatch action to toggle expansion state
        // This is just a placeholder; actual dispatch logic will depend on your setup
        console.log(\`Toggling item with id: \${id}\`);
    };
    return (
        <Paper>
            <Box>
                <Typography>{title}</Typography>
                <Button onClick={onToggle}>{isExpanded ? '▲' : '▼'}</Button>
            </Box>
            <Collapse in={isExpanded}>
                <Typography>{description}</Typography>
            </Collapse>
        </Paper>
    );
};

export default ListItem;
`;

export default snippet;
