// AUTO-GENERATED by generate-snippets.js
// Source: UseEffectParent.tsx
// Do not edit this file directly.

const snippet = `import { Box, Typography, Grid } from '@mui/material';
import { ContextOneProvider } from './ContextOne';
import { ContextTwoProvider } from './ContextTwo';
import { ContextThreeProvider } from './ContextThree';
import ContextOneConsumer from './components/ConsumerOne';
import ContextTwoConsumer from './components/ConsumerTwo';
import ContextThreeConsumer from './components/ConsumerThree';
import CombinedValueConsumer from './components/CombinedValueConsumer';
import TextForm from './TextForm';

const UseEffectParent = () => {
    return (
        <ContextOneProvider key="effect-version">
            <ContextTwoProvider key="effect-version">
                <ContextThreeProvider key="effect-version">
                    <ContextOneConsumer />
                    <ContextTwoConsumer />
                    <ContextThreeConsumer />
                    <CombinedValueConsumer />
                </ContextThreeProvider>
            </ContextTwoProvider>
        </ContextOneProvider>
    );
};

export default UseEffectParent;
`;

export default snippet;
