// AUTO-GENERATED by generate-snippets.js on 2025-10-23T16:20:24.439Z
// Source: CombinedValueConsumer.tsx
// Do not edit this file directly.

const snippet = `import { useAppContextThree } from '../ContextThree';
import { Box, Typography } from '@mui/material';

const CombinedValueConsumer = () => {
    const { combinedTextValThree } = useAppContextThree();

    return (
        <Box>
            <Typography>useEffect Combined Value Consumer</Typography>
            <Typography>Value: {combinedTextValThree}</Typography>
        </Box>
    );
};

export default CombinedValueConsumer;
`;

export default snippet;
