// AUTO-GENERATED by generate-snippets.js
// Contains explanation exports extracted from snippet sources
//   context.tsx
//   InfiniteRendersExample.tsx
//   components\LastUpdated.tsx
//   components\ParentControls.tsx
//   components\RegularChild.tsx

export const contextExplanation =
    'This is a simple context to illustrate how you might get into an infinite render loop.';
export const infiniteRendersExampleExplanation =
    'Parent component rendering a provider and components that use the context.';
export const lastUpdatedExplanation =
    'A child component that is NOT memoized and uses a non-memoized function in a useEffect, causing infinite renders.';
export const parentControlsExplanation =
    'Component that calls the handleIncrement function from the context.';
export const regularChildExplanation =
    'A child component that is NOT memoized and uses a non-memoized function in a useEffect, causing infinite renders.';
