// AUTO-GENERATED by generate-snippets.js on 2025-10-23T15:09:13.228Z
// Source: InfiniteRendersExample.tsx
// Do not edit this file directly.

const snippet = `// Generate Snippet
import { Box, Typography, Container, Grid } from '@mui/material';
import RegularChild from './components/RegularChild';
import ParentControls from './components/ParentControls';
import styles from 'MemoizedComponents.module.scss';
import LastUpdatedDisplay from './components/LastUpdated';
import { InfiniteLoopProvider } from './context';

const InfiniteRendersExample = () => {
    return (
        <InfiniteLoopProvider>
            <ParentControls />
            <RegularChild />
            <LastUpdatedDisplay />
        </InfiniteLoopProvider>
    );
};

export default InfiniteRendersExample;
`;

export default snippet;
