// AUTO-GENERATED by generate-snippets.js
// Source: ExpensiveComponentBad.tsx
// Do not edit this file directly.

const snippet = `import React from 'react';
import { Paper, Typography } from '@mui/material';
import styles from 'MemoizedComponents.module.scss';

interface ExpensiveComponentBadProps {
    multiplier: number;
}

function calculateExpensiveValue(multiplier: number): number {
    console.log('❌ BAD: Recalculating expensive value on every render');
    return multiplier * 1000;
}

const ExpensiveComponentBad: React.FC<ExpensiveComponentBadProps> = ({
    multiplier,
}) => {
    // ❌ BAD: This will recalculate on every render
    const expensiveValue = calculateExpensiveValue(multiplier);

    return (
        <Paper>
            <Typography>Non-Memoized Calculation</Typography>
            <Typography>🔄 Recalculates on every render (expensive)</Typography>
            <Typography>Multiplier: {multiplier}</Typography>
            <Typography>Expensive Value: {expensiveValue}</Typography>
            <Typography>
                Check the console to see how often this logs during parent
                renders
            </Typography>
        </Paper>
    );
};

export default ExpensiveComponentBad;
`;

export default snippet;
