// AUTO-GENERATED by generate-snippets.js
// Source: MemoizedChildWithBadCallback.tsx
// Do not edit this file directly.

const snippet = `import React, { memo } from 'react';
import { Paper, Typography, Button } from '@mui/material';
import styles from 'MemoizedComponents.module.scss';

interface MemoizedChildWithBadCallbackProps {
    value: number;
    onIncrement: () => void;
    expensiveValue: number;
}

const MemoizedChildWithBadCallback = memo<MemoizedChildWithBadCallbackProps>(
    ({ value, onIncrement, expensiveValue }) => {
        return (
            <Paper>
                <Typography>Memoized Child + Non-Memoized Function</Typography>
                <Typography>
                    ⚠️ React.memo but new function props = Still re-renders
                </Typography>
                <Typography>Value: {value}</Typography>
                <Typography>Expensive Value: {expensiveValue}</Typography>
                <Button onClick={onIncrement}>Increment</Button>
            </Paper>
        );
    },
);

MemoizedChildWithBadCallback.displayName = 'MemoizedChildWithBadCallback';

export default MemoizedChildWithBadCallback;
`;

export default snippet;
