// AUTO-GENERATED by generate-snippets.js
// Source: MemoizedChild.tsx
// Do not edit this file directly.

const snippet = `import { memo } from 'react';
import { Paper, Typography, Button } from '@mui/material';
import styles from 'MemoizedComponents.module.scss';

interface MemoizedChildProps {
    value: number;
    onIncrement: () => void;
    expensiveValue: number;
}

const MemoizedChild = memo<MemoizedChildProps>(
    ({ value, onIncrement, expensiveValue }) => {
        return (
            <Paper>
                <Typography>Memoized Child Component</Typography>
                <Typography>✅ React.memo + useCallback = Optimized</Typography>
                <Typography>Value: {value}</Typography>
                <Typography>Expensive Value: {expensiveValue}</Typography>
                <Button onClick={onIncrement}>Increment</Button>
            </Paper>
        );
    },
);

MemoizedChild.displayName = 'MemoizedChild';

export default MemoizedChild;
`;

export default snippet;
