// AUTO-GENERATED by generate-snippets.js
// Source: ParentControls.tsx
// Do not edit this file directly.

const snippet = `import React from 'react';
import { Paper, Typography, TextField, Box } from '@mui/material';
import styles from 'MemoizedComponents.module.scss';

interface ParentControlsProps {
    unrelatedState: string;
    onUnrelatedStateChange: (value: string) => void;
    multiplier: number;
    onMultiplierChange: (value: number) => void;
    count1: number;
}

const ParentControls: React.FC<ParentControlsProps> = ({
    unrelatedState,
    onUnrelatedStateChange,
    multiplier,
    onMultiplierChange,
    count1,
}) => {
    return (
        <Paper>
            <Typography gutterBottom>🎛️ Parent State Controls</Typography>
            <Box>
                <TextField
                    label="Unrelated State (triggers all renders)"
                    value={unrelatedState}
                    onChange={(e) => onUnrelatedStateChange(e.target.value)}
                    fullWidth
                />
                <TextField
                    label="Multiplier"
                    type="number"
                    value={multiplier}
                    onChange={(e) => onMultiplierChange(Number(e.target.value))}
                    fullWidth
                />
                <Typography>
                    <strong>Count 1:</strong> {count1}
                </Typography>
            </Box>
        </Paper>
    );
};

export default ParentControls;
`;

export default snippet;
