// AUTO-GENERATED by generate-snippets.js
// Source: RegularChild.tsx
// Do not edit this file directly.

const snippet = `import { Paper, Typography, Button } from '@mui/material';
import styles from 'MemoizedComponents.module.scss';

interface RegularChildProps {
    value: number;
    onIncrement: () => void;
    expensiveValue: number;
}

const RegularChild: React.FC<RegularChildProps> = ({
    value,
    onIncrement,
    expensiveValue,
}) => {
    return (
        <Paper>
            <Typography>Regular Child Component</Typography>
            <Typography>🔄 Always re-renders (no React.memo)</Typography>
            <Typography>Value: {value}</Typography>
            <Typography>Expensive Value: {expensiveValue}</Typography>
            <Button onClick={onIncrement}>Increment</Button>
        </Paper>
    );
};

export default RegularChild;
`;

export default snippet;
