#!/usr/bin/env node
// generate-snippets.mjs
// Usage:
//   node generate-snippets.mjs [paths...]
//
// This version only generates a snippet if the source file begins with the line:
//   // Generate Snippet
//
// For each matching React component file (.tsx, .jsx, .ts, .js),
// it creates a sibling file named like "<lowerFirstBase>Snippet.ts"
// exporting the file's content as a string.

import { promises as fs } from 'node:fs';
import path from 'node:path';

const exts = new Set([".tsx", ".jsx", ".ts", ".js"]);
const now = new Date().toISOString();

const args = process.argv.slice(2);
const roots = args.length ? args : [process.cwd()];

async function* walk(dir) {
  const entries = await fs.readdir(dir, { withFileTypes: true });
  for (const entry of entries) {
    const res = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      const lower = entry.name.toLowerCase();
      if (["node_modules", ".git", "dist", "build", ".next", "out"].includes(lower)) continue;
      yield* walk(res);
    } else {
      yield res;
    }
  }
}

function looksLikeSnippetFile(file) {
  return /Snippet\.ts$/.test(file);
}

function shouldSkip(file) {
  const base = path.basename(file);
  if (looksLikeSnippetFile(base)) return true;
  if (/\.(test|spec)\./i.test(base)) return true;
  if (/\.stories\./i.test(base)) return true;
  if (/\.d\.ts$/i.test(base)) return true;
  return false;
}

function lowerFirst(s) {
  return s.length ? s[0].toLowerCase() + s.slice(1) : s;
}

function targetPathFor(srcPath) {
  const dir = path.dirname(srcPath);
  const ext = path.extname(srcPath);
  if (!exts.has(ext)) return null;
  const base = path.basename(srcPath, ext);
  const outBase = `${lowerFirst(base)}Snippet.ts`;
  return path.join(dir, outBase);
}

function toTemplateLiteralSafe(content) {
  return content.replaceAll("`", "\\`").replaceAll("${", "\\${");
}

function fileHeader(srcPath) {
  return `// AUTO-GENERATED by generate-snippets.mjs on ${now}\n// Source: ${path.basename(srcPath)}\n// Do not edit this file directly.\n`;
}

async function writeSnippet(srcPath, outPath, body) {
  const header = fileHeader(srcPath);
  const fileText = `${header}\nconst snippet = \`${toTemplateLiteralSafe(body)}\`;\n\nexport default snippet;\n`;

  const prev = await fs.readFile(outPath, "utf8").catch(() => null);
  if (prev === fileText) return { outPath, status: "unchanged" };
  await fs.writeFile(outPath, fileText, "utf8");
  return { outPath, status: "written" };
}

async function processFile(file) {
  if (shouldSkip(file)) return null;
  const ext = path.extname(file);
  if (!exts.has(ext)) return null;

  const outPath = targetPathFor(file);
  if (!outPath) return null;

  try {
    const body = await fs.readFile(file, "utf8");
    // Only process if the first line is exactly '// Generate Snippet'
    const firstLine = body.split(/\r?\n/, 1)[0].trim();
    if (firstLine !== "// Generate Snippet") return null;

    const result = await writeSnippet(file, outPath, body);
    return { src: file, out: outPath, ...result };
  } catch (err) {
    return { src: file, error: String(err) };
  }
}

(async () => {
  const results = [];
  for (const root of roots) {
    for await (const file of walk(root)) {
      const r = await processFile(file);
      if (r) results.push(r);
    }
  }

  const grouped = results.reduce(
    (acc, r) => {
      if (r.error) acc.errors.push(r);
      else if (r.status === "written") acc.written.push(r);
      else if (r.status === "unchanged") acc.unchanged.push(r);
      return acc;
    },
    { written: [], unchanged: [], errors: [] }
  );

  const rel = (p) => path.relative(process.cwd(), p) || p;

  if (grouped.written.length) {
    console.log("\nCreated/Updated:");
    for (const r of grouped.written) console.log(`  ${rel(r.out)}  ←  ${rel(r.src)}`);
  }
  if (grouped.unchanged.length) {
    console.log("\nUnchanged:");
    for (const r of grouped.unchanged) console.log(`  ${rel(r.out)}  (from ${rel(r.src)})`);
  }
  if (grouped.errors.length) {
    console.error("\nErrors:");
    for (const r of grouped.errors) console.error(`  ${rel(r.src)}: ${r.error}`);
    process.exitCode = 1;
  }
})();