// AUTO-GENERATED by generate-snippets.js on 2025-10-23T14:01:34.526Z
// Source: MemoizedComponentsContextExample.tsx
// Do not edit this file directly.

const snippet = `// Generate Snippet
import { Box, Typography, Container, Grid } from '@mui/material';
import { MemoizedComponentsProvider } from './context';
import RegularChildContext from './components/RegularChildContext';
import MemoizedChildContext from './components/MemoizedChildContext';
import MemoizedChildWithBadCallbackContext from './components/MemoizedChildWithBadCallbackContext';
import ExpensiveComponentBadContext from './components/ExpensiveComponentBadContext';
import ExpensiveComponentGoodContext from './components/ExpensiveComponentGoodContext';
import ParentControlsContext from './components/ParentControlsContext';
import styles from 'MemoizedComponents.module.scss';

const MemoizedComponentsExampleContent = () => {
    return (
        <Container maxWidth="lg">
            <ParentControlsContext />
            <RegularChildContext />
            <MemoizedChildWithBadCallbackContext />
            <MemoizedChildContext />
            <ExpensiveComponentBadContext />
            <ExpensiveComponentGoodContext />
        </Container>
    );
};

const MemoizedComponentsContextExample = () => {
    return (
        <MemoizedComponentsProvider>
            <MemoizedComponentsExampleContent />
        </MemoizedComponentsProvider>
    );
};

export default MemoizedComponentsContextExample;
`;

export default snippet;
