// AUTO-GENERATED by generate-snippets.js
// Source: ConsumerThree.tsx
// Do not edit this file directly.

const snippet = `import { Box, Typography } from '@mui/material';
import { useAppContextThree } from '../ContextThree';

const ContextThreeConsumer = () => {
    const { textValThree, lastUpdated } = useAppContextThree();
    return (
        <Box>
            <Typography>Context Three Consumer</Typography>
            <Typography>Value: {textValThree}</Typography>
            <Typography>Updated: {lastUpdated}</Typography>
        </Box>
    );
};

export default ContextThreeConsumer;
`;

export default snippet;
