// AUTO-GENERATED by generate-snippets.js on 2025-10-23T16:21:26.856Z
// Source: ConsumerOne.tsx
// Do not edit this file directly.

const snippet = `import { Box, Typography } from '@mui/material';
import { useAppContextOne } from '../ContextOne';

const ContextOneConsumer = () => {
    const { textVal, lastUpdated } = useAppContextOne();
    return (
        <Box>
            <Typography>Context One Consumer</Typography>
            <Typography>Value: {textVal}</Typography>
            <Typography>Updated: {lastUpdated}</Typography>
        </Box>
    );
};

export default ContextOneConsumer;
`;

export default snippet;
