// AUTO-GENERATED by generate-snippets.js on 2025-10-23T16:21:26.856Z
// Source: TextForm.tsx
// Do not edit this file directly.

const snippet = `import { TextField, Box } from '@mui/material';
import RenderCount from '../../../overall/RenderCount';
import { useAppContextOne } from './ContextOne';
import { useAppContextThree } from './ContextThree';
import { useAppContextTwo } from './ContextTwo';

const TextForm = () => {
    const { textVal, setTextVal } = useAppContextOne();
    const { textValTwo, setTextValTwo } = useAppContextTwo();
    const { textValThree, setTextValThree } = useAppContextThree();
    return (
        <Box>
            <TextField
                label="Context One Val"
                variant="outlined"
                value={textVal}
                onChange={(e) => setTextVal(e.target.value)}
            />
            <TextField
                label="Context Two Val"
                variant="outlined"
                value={textValTwo}
                onChange={(e) => setTextValTwo(e.target.value)}
            />
            <TextField
                label="Context Three Val"
                variant="outlined"
                value={textValThree}
                onChange={(e) => setTextValThree(e.target.value)}
            />
        </Box>
    );
};

export default TextForm;
`;

export default snippet;
