// AUTO-GENERATED by generate-snippets.js
// Source: ReduxParent.tsx
// Do not edit this file directly.

const snippet = `import { Box, Typography, Grid } from '@mui/material';
import TextForm from './TextForm';
import { useAppSelector } from '../../../store/hooks';
import { selectCombinedTextValThree } from './three.slice';
import SliceOneConsumer from './components/ConsumerOne';
import SliceTwoConsumer from './components/ConsumerTwo';
import SliceThreeConsumer from './components/ConsumerThree';

const CombinedValueConsumer = () => {
    const combinedTextValThree = useAppSelector(selectCombinedTextValThree);

    return (
        <Box
            sx={{
                p: 2,
                m: 1,
                border: '2px solid #ff6f00',
                borderRadius: 2,
                backgroundColor: '#1a1a1a',
                '&:hover': {
                    backgroundColor: '#2a2a2a',
                },
            }}
        >
            <Typography sx={{ color: '#ff6f00', fontWeight: 'bold' }}>
                Combined Value Consumer
            </Typography>
            <Typography>Combined Value: {combinedTextValThree}</Typography>
        </Box>
    );
};

const ReduxParent = () => {
    return (
        <>
            <Box
                sx={{
                    border: '2px solid #ff6f00',
                    borderRadius: 2,
                    p: 2,
                    mt: 2,
                    backgroundColor: '#1e1e1e',
                    position: 'relative',
                }}
            >
                {/* Redux Section Label */}
                <Box
                    sx={{
                        position: 'absolute',
                        top: -12,
                        left: 16,
                        backgroundColor: '#ff6f00',
                        color: 'white',
                        px: 2,
                        py: 0.5,
                        borderRadius: 1,
                        fontSize: '0.75rem',
                        fontWeight: 'bold',
                    }}
                >
                    REDUX STORE
                </Box>

                <Typography gutterBottom sx={{ color: '#ff6f00', mt: 2 }}>
                    Redux Version
                </Typography>
                <Typography paragraph sx={{ color: '#bbb' }}>
                    Redux selectors only trigger re-renders when selected state
                    changes
                </Typography>
                <Grid container spacing={2}>
                    <Grid item xs={12} sm={6}>
                        <SliceOneConsumer />
                    </Grid>
                    <Grid item xs={12} sm={6}>
                        <SliceTwoConsumer />
                    </Grid>
                    <Grid item xs={12} sm={6}>
                        <SliceThreeConsumer />
                    </Grid>
                    <Grid item xs={12} sm={6}>
                        <CombinedValueConsumer />
                    </Grid>
                    <Grid item xs={12}>
                        <TextForm />
                    </Grid>
                </Grid>
            </Box>
        </>
    );
};

export default ReduxParent;
`;

export default snippet;
