// AUTO-GENERATED by generate-snippets.js on 2025-10-23T14:37:25.010Z
// Source: ExpandableListExample.tsx
// Do not edit this file directly.

const snippet = `// Generate Snippet
import React, { useState, useCallback } from 'react';
import { Box, Typography, Container } from '@mui/material';
import ListItem from './components/ListItem';
import { listData } from './listData';
import styles from 'MemoizedComponents.module.scss';

const ExpandableListExample: React.FC = () => {
    const [expandedIndexRegular, setExpandedIndexRegular] = useState<
        number | null
    >(null);

    const handleToggleRegular = useCallback((index: number) => {
        setExpandedIndexRegular((prev) => (prev === index ? null : index));
    }, []);

    return (
        <Container maxWidth="lg">
            <Box>
                {listData.map((item, index) => (
                    <ListItem
                        key={item.id}
                        id={item.id}
                        title={item.title}
                        description={item.description}
                        isExpanded={expandedIndexRegular === index}
                        onToggle={() => handleToggleRegular(index)}
                    />
                ))}
            </Box>
        </Container>
    );
};

export default ExpandableListExample;
`;

export default snippet;
