// AUTO-GENERATED by generate-snippets.js
// Contains explanation exports extracted from snippet sources
//   ExpandableListExample.tsx
//   listData.ts
//   components\ListItem.tsx

export const expandableListExampleExplanation =
    'The parent component that handles rendering the list items and tracking the expanded item index.';
export const listDataExplanation =
    'Simple List Data that is mapped in the parent component.';
export const listItemExplanation = 'Individual list item that is NOT memoized.';
