// AUTO-GENERATED by generate-snippets.js on 2025-10-23T16:16:11.493Z
// Source: ConsumerTwo.tsx
// Do not edit this file directly.

const snippet = `// Generate Snippet
import { Box, Typography } from '@mui/material';
import { useAppContextTwo } from '../ContextTwo';

const ContextTwoConsumer = () => {
    const { textValTwo } = useAppContextTwo();
    return (
        <Box>
            <Typography>Context Two Consumer</Typography>
            <Typography>Value: {textValTwo}</Typography>
        </Box>
    );
};

export default ContextTwoConsumer;
`;

export default snippet;
