// AUTO-GENERATED by generate-snippets.js on 2025-10-23T16:16:11.493Z
// Source: ConsumerThree.tsx
// Do not edit this file directly.

const snippet = `// Generate Snippet
import { Box, Typography } from '@mui/material';
import { useAppContextThree } from '../ContextThree';

const ContextThreeConsumer = () => {
    const { textValThree } = useAppContextThree();
    return (
        <Box>
            <Typography>Context Three Consumer</Typography>
            <Typography>Value: {textValThree}</Typography>
        </Box>
    );
};

export default ContextThreeConsumer;
`;

export default snippet;
