// AUTO-GENERATED by generate-snippets.js
// Source: ExpensiveComponentGood.tsx
// Do not edit this file directly.

const snippet = `import { Paper, Typography } from '@mui/material';
import { useAppSelector } from 'store/hooks';
import {
    selectExpensiveValue,
    selectMultiplier,
} from '../memoizedComponents.slice';
import styles from 'MemoizedComponents.module.scss';

const ExpensiveComponentGood = () => {
    const multiplier = useAppSelector(selectMultiplier);
    const expensiveValue = useAppSelector(selectExpensiveValue);

    return (
        <Paper>
            <Typography>Memoized Calculation</Typography>
            <Typography>
                ✅ createSelector prevents expensive recalculations
            </Typography>
            <Typography>Multiplier: {multiplier}</Typography>
            <Typography>Expensive Value: {expensiveValue}</Typography>
            <Typography>
                Check the console to confirm that logging only occurs when the
                multiplier changes
            </Typography>
        </Paper>
    );
};

export default ExpensiveComponentGood;
`;

export default snippet;
