// AUTO-GENERATED by generate-snippets.js on 2025-10-23T16:57:07.739Z
// Source: MemoizedChildWithBadCallback.tsx
// Do not edit this file directly.

const snippet = `import { memo } from 'react';
import { Paper, Typography, Button } from '@mui/material';
import { useAppSelector, useAppDispatch } from '../../../store/hooks';
import {
    selectCount1,
    selectExpensiveValue,
    incrementCount1,
} from '../memoizedComponents.slice';
import styles from 'MemoizedComponents.module.scss';

const MemoizedChildWithBadCallback = memo(() => {
    const dispatch = useAppDispatch();
    const count1 = useAppSelector(selectCount1);
    const expensiveValue = useAppSelector(selectExpensiveValue);

    const handleIncrement = () => dispatch(incrementCount1());

    return (
        <Paper>
            <RenderCount componentName="MemoizedChildWithBadCallbackRedux" />
            <Typography>
                Memoized Child + Non-Memoized Function (Redux)
            </Typography>
            <Typography>
                ✅ React.memo + Redux action that doesn't need to be memoized.
            </Typography>
            <Typography>Value: {count1}</Typography>
            <Typography>Expensive Value: {expensiveValue}</Typography>
            <Button onClick={handleIncrement}>Increment</Button>
        </Paper>
    );
});

MemoizedChildWithBadCallback.displayName = 'MemoizedChildWithBadCallback';

export default MemoizedChildWithBadCallback;
`;

export default snippet;
