// AUTO-GENERATED by generate-snippets.js on 2025-10-23T16:57:07.739Z
// Source: ParentControls.tsx
// Do not edit this file directly.

const snippet = `import React from 'react';
import { Paper, Typography, TextField, Box } from '@mui/material';
import { useAppSelector, useAppDispatch } from 'store/hooks';
import {
    selectMultiplier,
    selectUnrelatedState,
    setUnrelatedState,
    setMultiplier,
    selectCount1,
} from '../memoizedComponents.slice';
import styles from 'MemoizedComponents.module.scss';

const ParentControls: React.FC = () => {
    const dispatch = useAppDispatch();
    const unrelatedState = useAppSelector(selectUnrelatedState);
    const multiplier = useAppSelector(selectMultiplier);
    const count1 = useAppSelector(selectCount1);

    return (
        <Paper>
            <Typography gutterBottom>🎛️ Redux State Controls</Typography>
            <Box>
                <TextField
                    label="Unrelated State (does not trigger memoized selectors)"
                    value={unrelatedState}
                    onChange={(e) =>
                        dispatch(setUnrelatedState(e.target.value))
                    }
                    fullWidth
                />
                <TextField
                    label="Multiplier"
                    type="number"
                    value={multiplier}
                    onChange={(e) =>
                        dispatch(setMultiplier(Number(e.target.value)))
                    }
                    fullWidth
                />
                <Typography>
                    <strong>Count 1:</strong> {count1}
                </Typography>
            </Box>
        </Paper>
    );
};

export default ParentControls;
`;

export default snippet;
