// AUTO-GENERATED by generate-snippets.js on 2025-10-23T16:57:07.739Z
// Source: RegularChild.tsx
// Do not edit this file directly.

const snippet = `import React from 'react';
import { Paper, Typography, Button } from '@mui/material';
import { useAppSelector, useAppDispatch } from '../../../store/hooks';
import {
    selectCount1,
    selectExpensiveValue,
    incrementCount1,
} from '../memoizedComponents.slice';
import styles from 'MemoizedComponents.module.scss';

const RegularChild: React.FC = () => {
    const dispatch = useAppDispatch();
    const count1 = useAppSelector(selectCount1);
    const expensiveValue = useAppSelector(selectExpensiveValue);

    return (
        <Paper>
            <RenderCount componentName="RegularChildRedux" />
            <Typography>Regular Child Component (Redux)</Typography>
            <Typography>🔄 Always re-renders (no React.memo)</Typography>
            <Typography>Value: {count1}</Typography>
            <Typography>Expensive Value: {expensiveValue}</Typography>
            <Button onClick={() => dispatch(incrementCount1())}>
                Increment
            </Button>
        </Paper>
    );
};

export default RegularChild;
`;

export default snippet;
