// AUTO-GENERATED by generate-snippets.js
// Source: ConsumerThree.tsx
// Do not edit this file directly.

const snippet = `import { Box, Typography } from '@mui/material';

const SliceThreeConsumer = () => {
    const textVal = useAppSelector(selectTextValThree);
    return (
        <Box>
            <Typography>Redux Three Consumer</Typography>
            <Typography>Value: {textVal}</Typography>
        </Box>
    );
};

export default SliceThreeConsumer;
`;

export default snippet;
