// AUTO-GENERATED by generate-snippets.js on 2025-10-23T15:46:55.984Z
// Source: ConsumerOne.tsx
// Do not edit this file directly.

const snippet = `// Generate Snippet
import { Box, Typography } from '@mui/material';

const SliceOneConsumer = () => {
    const textVal = useAppSelector(selectTextValOne);
    return (
        <Box>
            <Typography>Redux One Consumer</Typography>
            <Typography>Value: {textVal}</Typography>
        </Box>
    );
};

export default SliceOneConsumer;
`;

export default snippet;
