// AUTO-GENERATED by generate-snippets.js on 2025-10-23T15:46:55.984Z
// Source: ConsumerTwo.tsx
// Do not edit this file directly.

const snippet = `// Generate Snippet
import { Box, Typography } from '@mui/material';

const SliceTwoConsumer = () => {
    const textVal = useAppSelector(selectTextValTwo);
    return (
        <Box>
            <Typography>Redux Two Consumer</Typography>
            <Typography>Value: {textVal}</Typography>
        </Box>
    );
};

export default SliceTwoConsumer;
`;

export default snippet;
