// AUTO-GENERATED by generate-snippets.js on 2025-10-23T15:46:55.984Z
// Source: ConsumerThree.tsx
// Do not edit this file directly.

const snippet = `// Generate Snippet
import { Box, Typography } from '@mui/material';

const SliceThreeConsumer = () => {
    const textVal = useAppSelector(selectTextValThree);
    return (
        <Box>
            <Typography>Redux Three Consumer</Typography>
            <Typography>Value: {textVal}</Typography>
        </Box>
    );
};

export default SliceThreeConsumer;
`;

export default snippet;
