// AUTO-GENERATED by generate-snippets.js
// Source: ExpensiveComponentBadContext.tsx
// Do not edit this file directly.

const snippet = `import { Paper, Typography } from '@mui/material';
import { useMemoizedComponentsContext } from '../context';
import styles from 'MemoizedComponents.module.scss';

function calculateExpensiveValue(multiplier: number): number {
    console.log('❌ BAD: Recalculating expensive value on every render');
    return multiplier * 1000;
}

const ExpensiveComponentBadContext = () => {
    const { multiplier } = useMemoizedComponentsContext();

    // ❌ BAD: This will recalculate on every render
    const expensiveValue = calculateExpensiveValue(multiplier);

    return (
        <Paper>
            <Typography>Non-Memoized Calculation (Context)</Typography>
            <Typography>🔄 Recalculates on every render (expensive)</Typography>
            <Typography>Multiplier: {multiplier}</Typography>
            <Typography>Expensive Value: {expensiveValue}</Typography>
            <Typography>
                Check the console to see how often this logs when context
                updates
            </Typography>
        </Paper>
    );
};

export default ExpensiveComponentBadContext;
`;

export default snippet;
