// AUTO-GENERATED by generate-snippets.js
// Source: MemoizedChildContext.tsx
// Do not edit this file directly.

const snippet = `import { memo } from 'react';
import { Paper, Typography, Button } from '@mui/material';
import { useMemoizedComponentsContext } from '../context';
import styles from 'MemoizedComponents.module.scss';

const MemoizedChildContext = memo(() => {
    const { count1, handleIncrement2, expensiveValue } =
        useMemoizedComponentsContext();

    return (
        <Paper>
            <Typography>Memoized Child Component (Context)</Typography>
            <Typography>
                ⚠️ React.memo + Context + useCallback = Still re-renders when
                any context value changes
            </Typography>
            <Typography>Value: {count1}</Typography>
            <Typography>Expensive Value: {expensiveValue}</Typography>
            <Button onClick={handleIncrement2}>Increment</Button>
        </Paper>
    );
});

MemoizedChildContext.displayName = 'MemoizedChildContext';

export default MemoizedChildContext;
`;

export default snippet;
