// AUTO-GENERATED by generate-snippets.js
// Source: MemoizedChildWithBadCallbackContext.tsx
// Do not edit this file directly.

const snippet = `import { memo } from 'react';
import { Paper, Typography, Button } from '@mui/material';
import { useMemoizedComponentsContext } from '../context';
import styles from 'MemoizedComponents.module.scss';

const MemoizedChildWithBadCallbackContext = memo(() => {
    const { count1, handleIncrement1Bad, expensiveValue } =
        useMemoizedComponentsContext();

    return (
        <Paper>
            <Typography>
                Memoized Child + Non-Memoized Function (Context)
            </Typography>
            <Typography>
                ⚠️ React.memo + Context + Non-Memoized Function = Always
                re-renders
            </Typography>
            <Typography>Value: {count1}</Typography>
            <Typography>Expensive Value: {expensiveValue}</Typography>
            <Button onClick={handleIncrement1Bad}>Increment</Button>
        </Paper>
    );
});

MemoizedChildWithBadCallbackContext.displayName =
    'MemoizedChildWithBadCallbackContext';

export default MemoizedChildWithBadCallbackContext;
`;

export default snippet;
