// AUTO-GENERATED by generate-snippets.js
// Source: ParentControlsContext.tsx
// Do not edit this file directly.

const snippet = `import { Paper, Typography, TextField, Box } from '@mui/material';
import { useMemoizedComponentsContext } from '../context';
import styles from 'MemoizedComponents.module.scss';

const ParentControlsContext = () => {
    const {
        unrelatedState,
        setUnrelatedState,
        multiplier,
        setMultiplier,
        count1,
    } = useMemoizedComponentsContext();

    return (
        <Paper>
            <Typography gutterBottom>🎛️ Context State Controls</Typography>
            <Box>
                <TextField
                    label="Unrelated State (triggers ALL context consumers)"
                    value={unrelatedState}
                    onChange={(e) => setUnrelatedState(e.target.value)}
                />
                <TextField
                    label="Multiplier"
                    value={multiplier}
                    onChange={(e) => setMultiplier(Number(e.target.value))}
                />
                <Typography>
                    <strong>Count 1:</strong> {count1}
                </Typography>
            </Box>
        </Paper>
    );
};

export default ParentControlsContext;
`;

export default snippet;
