// AUTO-GENERATED by generate-snippets.js
// Source: RegularChildContext.tsx
// Do not edit this file directly.

const snippet = `import { Paper, Typography, Button } from '@mui/material';
import { useMemoizedComponentsContext } from '../context';
import styles from 'MemoizedComponents.module.scss';

const RegularChildContext = () => {
    const { count1, handleIncrement1Bad, expensiveValue } =
        useMemoizedComponentsContext();

    return (
        <Paper>
            <Typography>Regular Child Component (Context)</Typography>
            <Typography>🔄 Always re-renders (no React.memo)</Typography>
            <Typography>Value: {count1}</Typography>
            <Typography>Expensive Value: {expensiveValue}</Typography>
            <Button onClick={handleIncrement1Bad}>Increment</Button>
        </Paper>
    );
};

export default RegularChildContext;
`;

export default snippet;
