// AUTO-GENERATED by generate-snippets.js
// Source: MemoizedComponentsExample.tsx
// Do not edit this file directly.

const snippet = `import { Box, Typography, Container, Grid } from '@mui/material';
import RegularChild from './components/RegularChild';
import MemoizedChild from './components/MemoizedChild';
import MemoizedChildWithBadCallback from './components/MemoizedChildWithBadCallback';
import ExpensiveComponentBad from './components/ExpensiveComponentBad';
import ExpensiveComponentGood from './components/ExpensiveComponentGood';
import ParentControls from './components/ParentControls';
import styles from 'MemoizedComponents.module.scss';

const MemoizedComponentsExample = () => {
    return (
        <Container maxWidth="lg">
            <ParentControls />
            <RegularChild />
            <MemoizedChildWithBadCallback />
            <MemoizedChild />
            <ExpensiveComponentBad />
            <ExpensiveComponentGood />
        </Container>
    );
};

export default MemoizedComponentsExample;
`;

export default snippet;
