// AUTO-GENERATED by generate-snippets.js
// Source: ExpandableListExample.tsx
// Do not edit this file directly.

const snippet = `import { Box, Typography, Container } from '@mui/material';
import { useAppSelector } from 'store/hooks';
import { selectListData } from './expandableList.slice';
import ListItem from './components/ListItem';
import styles from 'MemoizedComponents.module.scss';

const ExpandableListReduxExample = () => {
    const listData = useAppSelector(selectListData);
    return (
        <Container maxWidth="lg">
            <Box>
                {listData.map((item, index) => (
                    <ListItem
                        key={item.id}
                        id={item.id}
                        title={item.title}
                        description={item.description}
                    />
                ))}
            </Box>
        </Container>
    );
};

export default ExpandableListReduxExample;
`;

export default snippet;
