// AUTO-GENERATED by generate-snippets.js on 2025-10-23T16:21:58.751Z
// Contains explanation exports extracted from snippet sources
//   expandableList.slice.ts
//   ExpandableListExample.tsx
//   listData.ts
//   components\ListItem.tsx

export const expandableList_sliceExplanation =
    'Expandable List Slice. This handles all of the state for the expandable list outside of a react context. It provides actions that components can use to update state. It also provides selectors that components can use to retrieve the pieces state that they care about. Components will not re-render unless their selector returns a new value.';
export const expandableListExampleExplanation =
    'The parent component that handles rendering the list items. Does not need to know the index of the expanded item.';
export const listDataExplanation = 'List Data';
export const listItemExplanation =
    'Individual list item that is NOT memoized. Uses a selector with the passed in ID to determine if it is expanded.';
