// AUTO-GENERATED by generate-snippets.js on 2025-10-23T16:22:05.461Z
// Source: LastUpdated.tsx
// Do not edit this file directly.

const snippet = `import { Paper, Typography } from '@mui/material';
import styles from 'MemoizedComponents.module.scss';
import { useInfiniteLoopContext } from '../context';

const LastUpdatedDisplay = () => {
    const { lastUpdated } = useInfiniteLoopContext();

    return (
        <Paper className={\`\${styles.card} \${styles.cardGreen}\`}>
            <RenderCount componentName="LastUpdatedDisplay" />
            <Typography
                variant="h6"
                className={\`\${styles.title} \${styles.titleGreen}\`}
            >
                Last Updated Display
            </Typography>
            <Typography>Last Updated: {lastUpdated}</Typography>
        </Paper>
    );
};

export default LastUpdatedDisplay;
`;

export default snippet;
