// AUTO-GENERATED by generate-snippets.js
// Source: LastUpdated.tsx
// Do not edit this file directly.

const snippet = `import { Paper, Typography } from '@mui/material';
import styles from 'MemoizedComponents.module.scss';
import { useInfiniteLoopContext } from '../context';

const LastUpdatedDisplay = () => {
    const { lastUpdated } = useInfiniteLoopContext();

    return (
        <Paper>
            <Typography>Last Updated Display</Typography>
            <Typography>Last Updated: {lastUpdated}</Typography>
        </Paper>
    );
};

export default LastUpdatedDisplay;
`;

export default snippet;
