// AUTO-GENERATED by generate-snippets.js on 2025-10-23T15:09:13.228Z
// Source: ParentControls.tsx
// Do not edit this file directly.

const snippet = `// Generate Snippet
import { Paper, Typography, Button, Box } from '@mui/material';
import styles from 'MemoizedComponents.module.scss';
import { useInfiniteLoopContext } from '../context';

const ParentControls = () => {
    const { handleIncrement } = useInfiniteLoopContext();
    return (
        <Paper>
            <Button onClick={handleIncrement}>Increment</Button>
        </Paper>
    );
};

export default ParentControls;
`;

export default snippet;
