// AUTO-GENERATED by generate-snippets.js
// Source: RegularChild.tsx
// Do not edit this file directly.

const snippet = `import { useRef, useEffect } from 'react';
import { Paper, Typography } from '@mui/material';
import styles from 'MemoizedComponents.module.scss';
import { useInfiniteLoopContext } from '../context';

const RegularChild = () => {
    const MAX_LOOPS = 25;
    const loopsRef = useRef(0);
    const { count, handleSetLastUpdated } = useInfiniteLoopContext();

    useEffect(() => {
        // Limit infinite loop for demo purposes
        if (loopsRef.current >= MAX_LOOPS || count === 0) {
            return;
        }
        loopsRef.current += 1;

        handleSetLastUpdated();
    }, [count, handleSetLastUpdated]);

    return (
        <Paper>
            <Typography>Infinite Loop Culprit Component</Typography>
            <Typography>
                ❌ Uses a non-memoized function in a useEffect causing infinite
                renders.
            </Typography>
        </Paper>
    );
};

export default RegularChild;
`;

export default snippet;
