// AUTO-GENERATED by generate-snippets.js on 2025-10-23T16:16:11.493Z
// Source: UseMemoParent.tsx
// Do not edit this file directly.

const snippet = `// Generate Snippet
import React from 'react';
import { Box, Typography, Grid } from '@mui/material';
import { ContextOneProvider } from './ContextOne';
import { ContextTwoProvider } from './ContextTwo';
import { ContextThreeProvider } from './ContextThree';
import ContextOneConsumer from './components/ConsumerOne';
import ContextTwoConsumer from './components/ConsumerTwo';
import ContextThreeConsumer from './components/ConsumerThree';
import CombinedValueConsumer from './components/CombinedValueConsumer';
import TextForm from './TextForm';

const UseMemoParent: React.FC = () => {
    return (
        <ContextOneProvider key="memo-version">
            <ContextTwoProvider key="memo-version">
                <ContextThreeProvider key="memo-version">
                    <ContextOneConsumer />
                    <ContextTwoConsumer />
                    <ContextThreeConsumer />
                    <CombinedValueConsumer />
                    <TextForm />
                </ContextThreeProvider>
            </ContextTwoProvider>
        </ContextOneProvider>
    );
};

export default UseMemoParent;
`;

export default snippet;
