// AUTO-GENERATED by generate-snippets.js
// Source: ListItem.tsx
// Do not edit this file directly.

const snippet = `import React from 'react';
import { Paper, Typography, Button, Collapse, Box } from '@mui/material';
import styles from 'MemoizedComponents.module.scss';

interface ListItemProps {
    id: number;
    title: string;
    description: string;
    isExpanded: boolean;
    onToggle: () => void;
}

const ListItem: React.FC<ListItemProps> = ({
    id,
    title,
    description,
    isExpanded,
    onToggle,
}) => {
    return (
        <Paper>
            <Box>
                <Typography>{title}</Typography>
                <Button>{isExpanded ? '▲' : '▼'}</Button>
            </Box>
            <Collapse in={isExpanded}>
                <Typography>{description}</Typography>
            </Collapse>
        </Paper>
    );
};

export default ListItem;
`;

export default snippet;
